- snooty.toml
- source/includes/admonitions/fact-mdb-shell-beta.rst
- source/index.txt
Hey @mmarcon, I'd appreciate your eyes on this first draft of the landing page for the MongoDB Shell.
Some notes for context:
- This content is largely modeled after the [existing shell docs](https://docs.mongodb.com/manual/mongo/)
- We will be handling the download / installation instructions in a separate ticket, as well as fleshing out the "Learn More" section at a later date.
- Included in this draft is a skeleton for how we want to shape the rest of the docs. Even though we are linking out to the existing manual docs for command reference, I think it would be helpful to include a baseline "Getting Started" with basic CRUD / aggregation.
Some questions:
1. Just confirming the product name is "MongoDB Shell"? Asking because in the [product …
> (DOCSP-10354): Landing page

- source/reference.txt
- source/reference/commands.txt
- source/reference/methods.txt
Staged: [Available Methods](https://docs-mongodbcom-staging.corp.mongodb.com/eb3d0c6/mongodb-shell/docsworker/DOCSP-10363/reference/methods)
Hey @mmarcon, in looking at the [output of the available new shell methods](https://mongodb.slack.com/files/UD96QJACS/F014EKV00BA/untitled?origin_team=T024FNNHU&origin_channel=Vall_threads) there are some methods in the output which we do not document on the [legacy mongo shell docs](https://docs.mongodb.com/manual/reference/method/).
I wanted to list them here just to see if they were maybe new methods, or wrappers for some other method?
* Collection Methods
* convertToCapped (this looks to be a [command](https://docs.mongodb.com/manual/reference/command/convertToCapped/), so I'm wondering if there is now a wrapper for this command?)
* exists
* …
> (DOCSP-10363): Add available methods

- source/includes/steps-install-shell-windows.yaml
- source/index.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-10356)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bb5b8b4/mongodb-shell/docsworker/DOCSP-10356/#download-and-install-the-mdb-shell)
Question for review: should there be an unzip procedure in step 4? I decided not to include one because unzipping can be done in many simple ways, including dragging the contents of the .zip folder out of the folder. Covering multiple Windows unzipping methods seems outside of scope and choosing one that works for all Windows versions overcomplicates later versions.
The procedure in step 5 covers Windows 10, 8, and 7. It's not very different for Vista and XP.
> (DOCSP-10356) Windows install procedure

- snooty.toml
- source/crud.txt
- source/crud/delete.txt
- source/crud/insert.txt
- source/crud/read.txt
- source/crud/update.txt
- source/includes/admonitions/note-natural-sort-order.rst
- source/includes/fact-sample-data-examples.rst
- source/reference/methods.txt
Staged: [Perform CRUD Operations](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker/DOCSP-10504/crud) plus sub-pages.
Questions for review
- What do you think about the flow here where we highlight the Atlas sample data? I wanted to insert data into a fresh collection, so they at least have something to work with if they don't want to spin up an Atlas cluster.
- There is a little bit of inconsistency between using `example` blocks and going with "For example..." prose. Lmk if you have a preference or if you think we should standardize more than what's done here.
> (DOCSP-10504): CRUD ops for mongosh

- source/includes/steps-install-shell-base.yaml
- source/includes/steps-install-shell-macos-homebrew.yaml
- source/includes/steps-install-shell-macos.yaml
- source/index.txt
- source/install.txt
Scope of Changes:
- Moved Install Instructions to their own page. Motivation: This section was getting long and the home page was kind of losing its meaning. Instead, I'm trying to keep the scope home page to high-level, important features of the MongoDB Shell. This also provides symmetry with the rest of our docs where most often Install gets its own page.
- Added instructions for install with Homebrew.
- Tweaked instructions for package install. Specifically:
- Make mongosh executable
- Remove mongosh from quarantine
- Added a "Next Steps" section pointing users to the connection page.
Staging:
[Install the MongoDB Shell](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker/DOCSP-10539/install)
> (DOCSP-10539): Install tweaks for Homebrew

- source/connect.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-10666)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker/DOCSP-10666/connect)
Broke out **Local MongoDB Instance on a Non-Default Port** and **MongoDB Instance on a Remote Host** into bulleted lists to cover --host and --port options as well.
> (DOCSP-10666) Update mongosh connection page with --port and --host

- source/connect.txt
With next week's snooty release (on the 8th or 9th), we'll be standardizing on `:doc:`-style Atlas links (i.e. including the leading `/`). This PR addresses the one `:atlas:` link in this repository that didn't already have the leading `/`.
Staging: https://docs-mongodborg-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/atlas-link/connect *note* that the link in staging is currently broken because I'm building on the production autobuilder rather than the version we'll release next week. 
Workerpool: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5eff8258a025140d8c12fd39
> DOP-1208: fix one :atlas: link to use doc-style links

- source/includes/admonitions/fact-mdb-shell-beta.rst
- source/includes/steps-install-shell-base.yaml
- source/index.txt
- source/install.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11251/
> (DOCSP-11251): Clarify that MongoDB Shell and mongosh are synonymous

- snooty.toml
- source/connect.txt
- source/includes/admonitions/note-redact-credentials-command-history.rst
- source/index.txt
- source/logs.txt
- source/write-scripts.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-10991)
Stage:
- [Write Scripts for the The MongoDB Shell](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-10991/write-scripts)
- [Connect to A Different Deployment](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-10991/connect#connect-to-a-different-deployment) -- added link to new section
- [Retrieve MongoDB Shell Logs](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-10991/logs#retrieve-mongodb-shell-logs) - added note that connection credentials are redacted from the history but not the logs
few other small fixes
The scripting features were not yet documented. made sense to add those that are implemented here, too, while I was …
> (DOCSP-10991): add Mongo() and scripting docs

- source/connect.txt
- source/reference/methods.txt
- source/write-scripts.txt
Just to note for review, I'll also be updating the `passwordPrompt()` docs in the manual to reflect the mongosh limitation (separate ticket).
Staged: [User Management Methods](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11553-new/reference/methods#user-management-methods)
> (DOCSP-11553): Add user management methods

- source/reference/methods.txt
Tested all of these. They seem to work as expected.
Staged: [Server Status Methods](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11657/reference/methods#server-status-methods)
> (DOCSP-11657): Server status and info methods

- source/reference/methods.txt
The `enableMonitoring` method is bugged. Issue raised with engineering and they should have a fix out tomorrow. Documenting these as if they all work.
Staged: [Free Monitoring Methods](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11658/reference/methods#free-monitoring-methods)
> (DOCSP-11658): Free monitoring methods

- source/reference/access-mdb-shell-help.txt
JIRA: [DOCSP-11439](https://jira.mongodb.org/browse/DOCSP-11439?)
Staged: [BSON class help](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11439/reference/access-mdb-shell-help#bson-class-help)
Need to follow up with tech review because not all .help() methods added in [the mongosh commit](https://github.com/mongodb-js/mongosh/commit/96a730fc05e4c226e9c365e971751bf0f362af1b) seem to be working.
The following classes' help methods don't work in mongosh:
- `bsonsize`
- `MD5`
- `UUID`
- `HexData`
They return `TypeError: <className>.help is not a function`
> (DOCSP-11439): BSON class help

- source/reference/methods.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-11793)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11793/reference/methods#bulk-operation-methods)
> DOCSP-11793: [MONGOSH] Support Bulk operation methods

- snooty.toml
- source/changelog.txt
- source/index.txt
- source/reference/access-mdb-shell-help.txt
- source/run-commands.txt
New updates for behavior when pressing ctrl+c in the shell, as well as the breaking change (compared to legacy mongo) for Command Exceptions. Moved the CRUD and Agg Pipeline docs to sub-pages of this new page.
Staged: [Run Commands in mongosh](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12243/run-commands)
Also updated behavior in Changelog. [Staging - v3.0.1 Behavior Updates](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12243/changelog#v0-3-1)
> (DOCSP-12243): Add Run Commands page and some command behaviors

- snooty.toml
- source/includes/steps-install-shell-base.yaml
- source/includes/steps-install-shell-linux-deb.yaml
- source/includes/steps-install-shell-linux-generic.yaml
- source/includes/steps-install-shell-linux-rpm.yaml
- source/includes/steps-install-shell-macos.yaml
- source/includes/steps-install-shell-windows.yaml
- source/install.txt
Added tabs to the Linux tab for each package / Linux distro supported. If you think there's a better way to structure this, happy to discuss.
Staged: [Install mongosh](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11649/install#install-mongosh)
> (DOCSP-11649): Update install instructions for .deb and .rpm

- source/reference/methods.txt
Includes [DOCSP-13309](https://jira.mongodb.org/browse/DOCSP-13309), [DOCSP-13311](https://jira.mongodb.org/browse/DOCSP-13311), and [DOCSP-12627](https://jira.mongodb.org/browse/DOCSP-12627).
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12627/reference/methods)
> DOCSP-12627: [MONGOSH] Transaction, Session, and Replica Set Config methods

- source/reference/methods.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-13551)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13551/reference/methods)
> DOCSP-13551: [MONGOSH] Support readConcern on cursor

- source/index.txt
- source/logs.txt
- source/reference/compatibility.txt
- source/reference/methods.txt
- source/write-scripts.txt
This is the first addition to what will ultimately be a page describing all compatibility changes between the mongo shell and mongosh. Currently I just put this on the top level ToC, but we may find that it lives better under Reference, or some other section.
Also did a bit of tweaking to some page titles.
JIRA: [DOCSP-13189](https://jira.mongodb.org/browse/DOCSP-13189)
Staged: [Compatibility Changes](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13189/reference/compatibility)
> (DOCSP-13189): Remove deprecated CRUD commands

- source/install.txt
- source/reference/methods.txt
These updates cover all tickets in the main [FLE ticket](https://jira.mongodb.org/browse/DOCSP-14006) (which has linked subtasks)
Note: We will be adding a new section for Azure / GCP support for FLE (with examples) shortly after this PR. The main purpose of this PR is to add the new FLE methods to the `mongosh` methods page.
Staging:
- [Install docs](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13918/install/#procedure) (Homebrew notice)
- [mongosh methods](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13918/reference/methods/)
> FLE documentation updates

- snooty.toml
- source/changelog.txt
- source/field-level-encryption.txt
- source/includes/fact-getkey-options.rst
- source/includes/steps-aws-kms.yaml
- source/includes/steps-azure-vault.yaml
- source/includes/steps-gcp-kms.yaml
- source/includes/steps-local-keyfile.yaml
- source/index.txt
This PR adds a new CSFLE landing page, including:
-  Brief CSFLE overview, linking back to Manual
-  New tab layout for all four supported KMS providers:
1. AWS KMS (previously supported, but undocumented)
2. Azure Vault (new with 0.8.0)
3. GCP KMS (new  with 0.8.0)
4. Local Keystore (previously supported, but undocumented)
_NOTES_ 
- I don't presently have a way of testing against an active KMS for any of these platforms, so I have provided my best guesses. Please validate if you, the reviewer, have such access!
- Please let me know if I can provide better, more practical example key names / location names / etc. Or if user params should be indicated in a different manner, perhaps with "< exampleText >". I hesitate to use caps or camelcase, supposing that upstream might not support case …
> DOCSP-14691 add shell csfle section

- source/reference/options.txt
- source/run-commands.txt
This updates the existing docs to change .mongorc.js to .mongoshrc.js
https://jira.mongodb.org/browse/DOCSP-15881
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-15881-update-mongorc.js-file-name/run-commands/#.mongoshrc.js-file
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-15881-update-mongorc.js-file-name/reference/options/#std-option-mongosh.--norc
> DOCS-15881 rename .mongorc.js to .mongoshrc.js

- source/includes/steps-install-shell-linux-deb.yaml
- source/includes/steps-install-shell-linux-rpm.yaml
JIRA: https://jira.mongodb.org/browse/DOCSP-16028
Staged: [Install mongosh](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16028/install/)
Changes can be found under the "Linux" tab. See both the `.deb` and `.rpm` sub-tabs.
> (DOCSP-16028): Rename Linux packages from mongosh to mongodb-mongosh

- source/includes/steps-install-shell-base.yaml
- source/includes/steps-install-shell-macos.yaml
- source/install.txt
JIRA: [DOCSP-16174](https://jira.mongodb.org/browse/DOCSP-16174)
Staged: [install mongosh](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16174/install/)
Summary of changes:
- On macOS, we’re using .zip instead of .tgz, so the filenames and extraction commands need to be adjusted
- The file suggests copying mongosh to e.g. /usr/local/bin – The mongosh-mongocryptd from the package needs to be copied as well, to /usr/local/libexec or /usr/local/bin as well (or generally ../libexec or ./ when seen relative from the mongosh binary itself)
Note: The JIRA ticket also mentions that the “macOS may prevent mongosh from running after installation” seems outdated, but I could not verify this in testing, so leaving this step in the procedure for now.
> (DOCSP-16174): install page fixups

- source/includes/steps-install-shell-windows-msi.yaml
- source/install.txt
.msi install was added in v0.13.1
JIRA: [DOCSP-16177](https://jira.mongodb.org/browse/DOCSP-16177)
STAGED: [Installation Docs](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16177/install/)
> (DOCSP-16177): Add .msi install instructions

- source/index.txt
- source/reference/compatibility.txt
- source/reference/data-types.txt
This change updates the type information to state that certain numbers are entered in mongosh as int32 rather than double. It also adds a warning that updating the same database with mongo and mongosh may result in data inconsistency.
https://jira.mongodb.org/browse/DOCSP-15687
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-15687-numeric-values-stored-as-int32/reference/data-types/
> DOCSP-15687 numeric values stored as int32

- source/includes/steps-install-shell-macos-homebrew.yaml
JIRA: [DOCSP-16363](https://jira.mongodb.org/browse/DOCSP-16373)
STAGED: [Install mongosh](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16373/install/) (see macOS tab for Homebrew instructions)
> (DOCSP-16373): Remove MongoDB tap step from homebrew install

- source/changelog.txt
- source/write-scripts.txt
This update removes mention of `.load` and replaces them with the `load()` method.
JIRA: [DOCSP-16326](https://jira.mongodb.org/browse/DOCSP-16326)
STAGED: [Execute a JavaScript File](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16326/write-scripts/#execute-a-javascript-file)
> (DOCSP-16326): Remove mentions of .load

- source/reference/compatibility.txt
- source/reference/data-types.txt
This change updates the information on type changes in mongosh compared to mongo shell. 
In addition to the content changes, the layout has been reorganized and several examples have been consolidated in one section.
STAGING:
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16365-align-mongosh-types-with-driver-types/reference/data-types/
>  DOCSP-16365 align mongosh types with driver types

- source/includes/steps-view-logs.yaml
- source/logs.txt
Removing references to `pino` and related libraries gives us the freedom to change the logging library in the future while keeping a newline-delimited JSON as the format.
> Remove references to pino and related libraries.

- source/reference/configure-shell-settings.txt
This updates the docs to add info about the modes, a behavior section, and an example for the 'redactHistory' setting
https://jira.mongodb.org/browse/DOCSP-16438
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16438-redacted-history-is-ux-pain-point/reference/configure-shell-settings/
> DOCSP-16438 redacted history is UX pain point

- source/reference/data-types.txt
Documents the order of parameters for the Timestamp constructor 
JIRA
https://jira.mongodb.org/browse/DOCSP-17908
STAGING
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-17908-timestamp-argument-order/reference/data-types/#timestamp
> DOCSP-17908 Timestamp argument order

- snooty.toml
- source/require-external-modules.txt
- source/write-scripts.txt
Hi @addaleax , would you mind taking a look at these changes to the scripting docs for mongosh? The goal is to add more relevant examples that can be executed by users. Prior, we didn't really include examples of how to actually run scripts.
This is separate from (but related to) the work being done in [DOCSP-15619](https://jira.mongodb.org/browse/DOCSP-15619) for the differences between require() and load(). Those changes will be added as a new sub-page under the top-level [Write Scripts](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-18950/write-scripts/) page.
STAGED CHANGES:
[Write Scripts for mongosh](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-18950/write-scripts/)
> (DOCSP-18950): Improvements to writing scripts docs

- source/includes/fact-connect-prereqs.rst
- source/reference/methods.txt
- source/run-commands.txt
- source/telemetry.txt
Hi @addaleax , @mmarcon.
This update adds documentation for telemetry in mongosh. Would you mind taking a look when you have a chance?
JIRA:
https://jira.mongodb.org/browse/DOCSP-19437
STAGING:
[Configure Telemetry](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-19437/telemetry/)
[Telemetry Methods](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-19437/reference/methods/#telemetry-methods)
> (DOCSP-19437): mongosh telemetry

- source/changelog.txt
These notes need to be merged after the main update which is in the docs repo. 
https://jira.mongodb.org/browse/DOCSP-20167
[MONGOSH] release notes for mongo.getDBs mongo.getDBNames
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-20167-release-notes-mongogetDBs/changelog/#v0.13.1
> DOCSP-20167 release notes for mongo.getDBs

- source/includes/steps-install-shell-linux-deb.yaml
- source/install.txt
The jira ticket says it is ok to remove the note about mongocryptd. However, there is existing copy about using older platforms and mongosh is supported back to MongoDB 4.0. With that in mind I modified the copy to highlight dropping support for ubuntu 16.04 instead of removing the information entirely. 
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16135-matchserver-support-matrix/install/#considerations-for-ubuntu
https://jira.mongodb.org/browse/DOCSP-16135
[MONGOSH] Match server support matrix for OS/arch
> DOCSP-16135 match server support matrix

- source/reference/compatibility.txt
- source/reference/options.txt
These are updates in the mongosh repo to accompany updates in the server manual repo (DOCSP-21096)
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-21243-retryable-writes-enabled-by-default/reference/compatibility/#write-preference-behavior
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-21243-retryable-writes-enabled-by-default/reference/options/#std-option-mongosh.--retryWrites
https://jira.mongodb.org/browse/DOCSP-21243
[MONGOSH] Retryable writes enabled by default
> DOCSP-21243 retryable writes enabled by default

- source/includes/fact-call-limitations.rst
- source/reference/compatibility.txt
- source/write-scripts.txt
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-15571-productize-new-async-rewriter/reference/compatibility/#limitations-on-database-calls
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-15571-productize-new-async-rewriter/write-scripts/
https://jira.mongodb.org/browse/DOCSP-15571
[MONGOSH] Productize new async rewriter
> DOCSP-15571 productize new async writer

- source/reference/editor-mode.txt
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-22047-clarify-edit-autoload/reference/editor-mode/#editing-a-command
https://jira.mongodb.org/browse/DOCSP-22047
[MONGOSH] Clarify editor autoload
> DOCSP-22047 clarify edit autoload

- source/connect.txt
- source/reference/options.txt
STAGING
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-21466-support-for-CANONICALIZE_HOST_NAME/reference/options/#std-option-mongosh.--sspiHostnameCanonicalization
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-21466-support-for-CANONICALIZE_HOST_NAME/connect/#limitations
JIRA
https://jira.mongodb.org/browse/DOCSP-21466
[MONGOSH] Add support for CANONICALIZE_HOST_NAME checks in mongosh
> DOCSP-21466 support for CANONICALIZE_HOST_NAME

- source/includes/steps-install-shell-base.yaml
- source/includes/steps-install-shell-macos.yaml
- source/reference/methods.txt
Description:
Removed the chmod command for install instructions since shared libs dont need +x. Also updated the binary names for the renamed mongosh files which are now "mongosh_csfle_v1.dylib" for macOS and "mongosh_csfle_v1.so" for linux. Also had to update the link reference `:method:Bulk.tojson()` -> `:method:Bulk.toJSON()` as it was causing a build error.
Jira:
https://jira.mongodb.org/browse/DOCSP-22855
Build:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=628cf0d27cf5397525895d16
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-22855/install/#install-from-.zip-file-1 (macos tab)
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-22855/install/#procedure-2 (linux tab)
> Docsp-22855 update CSFLE binary names

- source/free-monitoring.txt
- source/index.txt
Description:
Added a new TOC entry to cover connecting to a community MongoDB cluster with MongoSH and a small page covering  how to enable and disable. The bulk of the information will be on the [server manual page](https://www.mongodb.com/docs/manual/administration/free-monitoring/) which is linked in this edit.
The other edit to add the cross repo ref in manual is [here](https://github.com/10gen/docs-mongodb-internal/pull/1207/files).
Jira:
https://jira.mongodb.org/browse/DOCSP-22993
Build:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=629f97457cf53975258a1d5e
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-22993/#free-monitoring
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlar …
> DOCSP-22993-Add-free-monitoring-callout

- snooty.toml
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-23864-update-server-version/install/#import-the-public-key-used-by-the-package-management-system)   Visible on this page
[JIRA](https://jira.mongodb.org/browse/DOCSP-23864)
> DOCSP-23864 update server version

- source/reference/methods.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-23878-build-errors-getLastError/reference/methods/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23878)
Fixes some build errors. See DOCSP-23879 for the remaining errors.
> DOCSP-23878 getLastError

- source/reference/options.txt
Adds refs/labels to reference/options.txt that will serve as updated replacements for labels that point to the legacy mongo shell docs.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-24836/reference/options/
This PR only adds refs. There should not be any visible changes.
https://jira.mongodb.org/browse/DOCSP-24836
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=630694c933823a066bb6d571
> DOCSP-24836 adds refs/labels to reference/options.txt 

- source/reference/options.txt
[Stable API Options](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-24855/reference/options/#stable-api-options)
https://jira.mongodb.org/browse/DOCSP-24855
> DOCSP-24855 adds Stable API options

- source/reference/methods.txt
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-25065/reference/methods/#native-methods
https://jira.mongodb.org/browse/DOCSP-25065
> DOCSP-25065 adds isInteractive() and quit() to native methods

- source/changelog.txt
- source/reference/methods.txt
- source/reference/options.txt
- source/write-scripts.txt
- source/write-scripts/require-load-differences.txt
Addresses build errors related to mongosh native methods.
https://jira.mongodb.org/browse/DOCSP-25400
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=632cc1f39ef0f10115d89010
> DOCSP-25400 Resolve mongosh build errors for native methods

- source/index.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-25497-deprecation-note/#the-mdb-shell-versus-the-legacy-mongo-shell)
[JIRA](https://jira.mongodb.org/browse/DOCSP-25497)
> DOCSP-25497 note about depreciation

- source/reference/options.txt
Fixes an issue where the slash would not appear between "mongod" and "mongos" binary links.
https://jira.mongodb.org/browse/DOCSP-26624
Live docs (no slash): https://www.mongodb.com/docs/mongodb-shell/reference/options/#std-option-mongosh.--tlsCAFile
Staging link (issue fixed): https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-26624/reference/options/#std-option-mongosh.--tlsCAFile
> (DOCSP-26624): Fix mongod/mongos formatting

- source/changelog.txt
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-26805/changelog/#v1.6.1
https://jira.mongodb.org/browse/DOCSP-26805
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=638a31fbed8015c14b367660
> DOCSP-26805 mongosh 1.6.1 release notes

- source/connect.txt
- source/includes/fact-connect-prereqs.rst
The goal here is to remove the clunky ``.. example::`` admonitions on this page and replace them with in-line examples. I also cleaned up some of the wording where appropriate.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13713/connect/
https://jira.mongodb.org/browse/DOCSP-13713
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=638a38f2ed8015c14b37d44f
> (DOCSP-13713): Improve layout of connect page

- source/includes/steps-install-shell-linux-rpm.yaml
This PR updates the MDB version used in Amazon Linux instructions from 5.0 > 6.0. Note that I have not tested this myself, and am just using the same versioning used on the RHEL tab.
https://jira.mongodb.org/browse/DOCSP-27120
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-27120/install/ (Linux tab > .rpm tab)
> (DOCSP-27120): fix mdb version on amazon install instructions

- source/connect.txt
- source/reference/compatibility.txt
The coded link in the old and new shell both point to the same dochub reference. This update makes the landing code generic so that reference will work for both shells. 
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-27869-dochub-conflict-update/connect/#non-genuine-deployments)
[JIRA](https://jira.mongodb.org/browse/DOCSP-27869)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6425e78866f244bf57cea902)
> DOCSP-27869 dochub conflict update

- source/reference/configure-shell-settings-api.txt
Corrects `config.set()` example.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-28986/reference/configure-shell-settings-api/#behavior-with-configuration-file
https://jira.mongodb.org/browse/DOCSP-28986
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64302024b49106a49823f6db
> DOCSP-28986 corrects config.set() example

- source/install.txt
Request was made in #docs to explicitly mention that we don't support amazon Linux 2023. We will support amazon Linux 2023 in the next mongosh release, 1.8.1, after which we will need to update this section again.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-29075/install/
https://jira.mongodb.org/browse/DOCSP-29075
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=643564b4b49106a4981a644c
> (DOCSP-29075): Install page updates to clarify amazon 2023 support

- source/crud.txt
- source/reference.txt
- source/snippets.txt
Toctrees no longer produce visible output so the `.. class:: hidden` directive isn't doing anything anyways. We're removing support for it in a forthcoming Snooty release, so might as well clean it up and avoid a warning in your logs in advance. Cheers!
> remove unnecessary (and deprecated) class directives

- source/logs.txt
Removing `.` from log path for correctness.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-25783/logs/#view-mdb-shell-command-history
https://jira.mongodb.org/browse/DOCSP-25783
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6467c3c8df0f8173e91106f9
> DOCSP-25783 Correct Log Paths

- source/connect.txt
- source/reference/options.txt
Documention new OIDC mongosh options and connection
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-28126/connect/#connect-with-openid-connect 
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-28126/reference/options/#authentication-options
https://jira.mongodb.org/browse/DOCSP-28126
Build Error for `authentication-oidc` is because that page has not been merged into the feature branch yet. 
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6493079e259a8493e566f266
> DOCSP-28126 OIDC mongosh options and connection

- source/includes/steps-install-shell-linux-deb.yaml
- source/install.txt
Add jammy install instructions for mongosh
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-28700/install/ (Linux tab > deb tab)
https://jira.mongodb.org/browse/DOCSP-28700
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6492fb55259a8493e5634d67
> (DOCSP-28700): Update mongosh install instructions for jammy

- source/reference/options.txt
Note that SCRAM-SHA-256 is the default user auth mechanism
[Options: authenticationMechanism](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCS-15627-note-SCRAM-default-SHA-256/reference/options/#std-option-mongosh.--authenticationMechanism)
https://jira.mongodb.org/browse/DOCS-15627
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b6d9a787b3b3604683ad7a
> DOCS-15627 Noted SCRAM-SHA-256 as default user auth mechanism

- source/includes/examples/ex-build-info-command.rst
- source/includes/examples/ex-build-info-flag.rst
- source/includes/fact-query-driver-versions.rst
- source/reference/methods.txt
- source/reference/options.txt
Adding a code example for the `mongosh --build-info` flag and adding a native method to the `reference/methods` page for the `buildInfo()` command.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-30813/reference/methods/#native-methods
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-30813/reference/options/#std-option-mongosh.--build-info
https://jira.mongodb.org/browse/DOCSP-30813
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d398cc67dbe9101034dbf7
> DOCSP-30813 Add buildInfo() Command and Binary Flag

- source/connect.txt
Adding LDAP connection details which are present in the manual at: https://www.mongodb.com/docs/manual/core/security-ldap-external/#connecting-to-a-mongodb-server-using-ldap-authorization but not currently listed under the connection page for `mongosh`.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-27860/connect/#connect-with-ldap
https://jira.mongodb.org/browse/DOCSP-27860
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d6610f67dbe91010e5d98c
> DOCSP-27860 Add LDAP Auth Connection Details

- source/changelog.txt
- source/connect.txt
- source/includes/boolean-logic-connection-strings.rst
Boolean logic updates for connection strings. Also fixed an unrelated minor formatting issue in the binary constructor output.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32212-parsing-logic/changelog/#v2.0.0
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32212-parsing-logic/connect/#limitations
https://jira.mongodb.org/browse/DOCSP-32212
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e6a04f57e37806c5b493f9
> DOCSP-32212-parsing-logic

- source/changelog.txt
Remove sharding version fields.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31861-deprecated-fields/changelog/#v2.0.0
https://jira.mongodb.org/browse/DOCSP-31861
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ed2d7a24fcc731b44bf07f
> DOCSP-31861-deprecated-fields

- snooty.toml
- source/includes/fact-compatibility.rst
- source/write-scripts.txt
Adds compatibility information and Atlas section under Open a Connection based on [Atlas Top 250 Guidance](https://docs.google.com/spreadsheets/d/1XrNidGxI1JKjt-toUxzS8WSwny4oeftg44IyMsEkEss/edit#gid=646834221).
https://preview-mongodbdavidhou17.gatsbyjs.io/mongodb-shell/DOCSP-32304/write-scripts/
https://jira.mongodb.org/browse/DOCSP-32304
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650df04c492df295cff2770b
> (DOCSP-32304): Add Atlas-centric content to Write Scripts page

- source/configure-mongosh.txt
- source/connect.txt
- source/crud.txt
- source/crud/delete.txt
- source/crud/insert.txt
- source/crud/read.txt
- source/crud/update.txt
- source/index.txt
- source/install.txt
- source/run-commands.txt
- source/write-scripts.txt
Hey @mdb-ashley!  I'm working on a ticket to add meta descriptions to the top 250 pages that don't have them.  Here are the ones for the mongosh repo.  In most cases, I copied and pasted a summarizing sentence from the page text, but please feel free to edit as you see fit.
Thanks!
Sarah
https://preview-mongodbsarahemlin.gatsbyjs.io/mongodb-shell/master/
https://jira.mongodb.org/browse/DOCSP-33172
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655bdb505b686d6bd943dcf6
> DOCSP-33172 added meta description for top 250 pages in docs-mongodb-shell

- source/reference/compatibility.txt
- source/reference/ejson/stringify.txt
Difference between mongosh and mongo in quoting keys and values goes beyond just --eval. Updated section to reflect this and show an example. 
https://preview-mongodbmongocaleb.gatsbyjs.io/mongodb-shell/DOCSP-34327/reference/compatibility/#object-quoting-behavior
https://jira.mongodb.org/browse/DOCSP-34327
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655e90bf13dc9d16ea3eac63
> mongosh and mongo quoting differences

- source/install.txt
- Fix inconsistencies regarding Amazon Linux version mentions on mongosh docs
- Make sure both Amazon Linux 2 and 2023 are mentioned. 
- [Supported OS table](https://preview-mongodbajhuhmdb.gatsbyjs.io/mongodb-shell/DOCSP-35222-amazon-compatibility-consistency/install/#supported-operating-systems)
- [Linux .rpm tab](https://preview-mongodbajhuhmdb.gatsbyjs.io/mongodb-shell/DOCSP-35222-amazon-compatibility-consistency/install/#supported-platforms-1)
https://jira.mongodb.org/browse/DOCSP-35222
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65987ae4dcc0144a517dec9e
> DOCSP-35222 Add Mentions of Amazon Linux 2023

- source/includes/fact-mongoshrc-loading.rst
- Adds title to admonition to clarify that it's talking about legacy shell configuration.
https://preview-mongodbajhuhmdb.gatsbyjs.io/mongodb-shell/DOCSP-35214-mongoshrc-config/mongoshrc/
https://jira.mongodb.org/browse/DOCSP-35214
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65aed7f56a2f0dd1df13ef89
> DOCSP-35214 .mongoshrc configuration file

- source/changelog.txt
- Release notes for mongosh 2.1.3
- also adds jira link for 2.1.0
https://preview-mongodbajhuhmdb.gatsbyjs.io/mongodb-shell/DOCSP-35144-mongosh.2.1.3-release/changelog/#v2.1.3
https://jira.mongodb.org/browse/DOCSP-35144
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c3f5176b2f17c95aec833c
> DOCSP-35144 Mongosh 2.1.3 RN

- source/logs.txt
document cap for number of log files
https://preview-mongodbkanchanamongodb.gatsbyjs.io/mongodb-shell/DOCSP-31008/logs/#log-retention
https://jira.mongodb.org/browse/DOCSP-31008
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65cf8f647111165982502075
> DOCSP-31008 document cap for number of log files

- source/changelog.txt
Shell 2.2.2 release notes.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-38001-shell-release-notes-2.2.2/changelog/#v2.2.2
https://jira.mongodb.org/browse/MONGOSH-1748
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660300f86fc5f048501b3e87
> DOCSP-38001-shell-release-notes-2.2.2

- source/reference/options.txt
Fixes typo in connection string on Options page.
Example block for [--host](https://preview-mongodbkennethdyer.gatsbyjs.io/mongodb-shell/DOCSP-33875-mongosh-typo/reference/options/#std-option-mongosh.--host)
[DOCSP-33875](https://jira.mongodb.org/browse/DOCSP-33875)
* [2024-04-11](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661851b93a5920a2915b3c66)
* [2024-04-12](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66197a273a5920a2919fed47)
> DOCSP-33875 Fixes mongosh typo

- source/snippets/reference.txt
Adding text to the snippets reference page 
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-shell/DOCSP-38360/snippets/reference/
https://jira.mongodb.org/browse/DOCSP-38360
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e2c6ccf5bec1c29c0bcd2
> DOCSP-38360 filling out snippets reference page

- source/includes/steps-install-shell-base.yaml
- source/includes/steps-install-shell-macos.yaml
- Updating file extension in step 4 macOS install instructions, to `sudo cp mongosh_crypt_v1.dylib /usr/local/lib/`
I think existing info warnings in BL, are not relevant to this PR:
```
INFO(includes/steps-install-shell-linux-deb.yaml:0ish): Detect tabs that contain tabs that contain procedures: : "tabs tab tabs tab include procedure" 
INFO(includes/steps-install-shell-linux-rpm.yaml:0ish): Detect tabs that contain tabs that contain procedures: : "tabs tab tabs tab include procedure" 
INFO(includes/steps-install-shell-linux-generic.yaml:0ish): Detect tabs that contain tabs that contain procedures: : "tabs tab tabs tab include procedure" 
```
(MacOS Tab)
https://preview-mongodbianfmongodb.gatsbyjs.io/mongodb-shell/DOCSP-41453/install/
https://jira.mongodb.org/browse/DOCSP-41453 …
> DOCSP-41453 macOS-install-instructions

- source/reference/methods.txt
`db.collection.getShardVersion()` description contained a link to the database command `getShardVersion` which has been deprecated. As a result, the link 404s.
This update removes the broken link and replaces the description with a brief description of the method's functionality.
https://preview-mongodbjwilsonmdb.gatsbyjs.io/mongodb-shell/DOCSP-41500/reference/methods/#:~:text=db.collection.getShardVersion()
https://jira.mongodb.org/browse/DOCSP-41500
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6696a16526eba795526fd297
> DOCSP-41500 remove 404 link to deprecated command

- source/includes/steps-install-shell-base.yaml
Fixes command mistype in mongosh install doc.
https://preview-mongodbjmdmongo.gatsbyjs.io/mongodb-shell/DOCSP-42501/install/#add-the-downloaded-binaries-to-your-path-environment-variable-1
**Note to reviewer**: You may need to click through (Linux -> .tgz) to see the updated step 4 "Add the downloaded binaries to your PATH environment variable."
https://jira.mongodb.org/browse/DOCSP-42501
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bbaffe8383957117cbeedd
> DOCSP-42501 fixes command mistype in mongosh install doc

- source/reference/options.txt
- Removing duplicate `shell` typo from options page.
https://preview-mongodbianfmongodb.gatsbyjs.io/mongodb-shell/DOCSP-42517/reference/options/#connection-options
https://jira.mongodb.org/browse/DOCSP-42517
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66be1eb68e811ae67225b5c9
> DOCSP-42517-remove-duplicate-shell

- source/changelog.txt
DOCSP-42955 mongosh v2.3.0 RN fix
Adds "removes support for out-of-the-box support for automatic encryption on deprecated Linux operating systems" to [MONGOSH-1550](https://jira.mongodb.org/browse/MONGOSH-1550) desc in the release notes for mongosh 2.3.0.
https://preview-mongodbjmdmongo.gatsbyjs.io/mongodb-shell/DOCSP-42955/changelog/#v2.3.0
https://jira.mongodb.org/browse/DOCSP-42955
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66cc9fc725dc1b90c7002877
> DOCSP-42955 mongosh v2.3.0 RN fix

- source/reference/options.txt
Fixed typo on options page
https://preview-mongodbgmillermdb.gatsbyjs.io/mongodb-shell/DOCSP-42673-typo-options/reference/options/#:~:text=client-side%20field%20level%20encryption.%20for%20the
https://jira.mongodb.org/browse/DOCSP-42673
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66da15a9f062608452cf95c8
> DOCSP-42673-typo-options

- config/redirects
Add a redirect from https://www.mongodb.com/docs/mongodb-shell/free-monitoring/ to the shell docs landing page.
Output for `mut-redirects config/redirects`:
`Redirect 301 /docs/mongodb-shell/free-monitoring https://www.mongodb.com/docs/mongodb-shell/`
N/A
https://jira.mongodb.org/browse/DOCSP-44183
> DOCSP-44183-free-monitoring-redirect

- source/reference/data-types.txt
- Document `Double` type in `mongosh`
- moved paragraph on default number type being int vs. double to a note between the Double and Integer sections for visibility with both sections.
https://deploy-preview-362--docs-mongodb-shell.netlify.app/reference/data-types/#double
https://jira.mongodb.org/browse/DOCSP-44585
> DOCSP-44585-double-type

- source/reference/compatibility.txt
[DOCSP-44560](https://jira.mongodb.org/browse/DOCSP-44560) notes that `mongosh` converts undefined to null during write operations, unlike the legacy `mongo` shell; this is not properly documented in the mongosh docs, so this PR adds this info to the [Compatibility Changes w/ Legacy `mongo` shell page](https://www.mongodb.com/docs/mongodb-shell/reference/compatibility/#compatibility-changes-with-legacy-mongo-shell)
https://deploy-preview-364--docs-mongodb-shell.netlify.app/reference/compatibility/#undefined-values
https://jira.mongodb.org/browse/DOCSP-45058
> DOCSP-45058-mongosh-undefined-behavior

- source/reference/compatibility.txt
Couple changes made in the[ "Undefined Values"|https://www.mongodb.com/docs/mongodb-shell/reference/compatibility/#undefined-values] section of the "Compatibility Changes with Legacy `mongo` Shell page: 
1. Section mentions that `mongosh` represents any stored BSON value as null. So if you’ve stored a BSON undefined value with some other tool—e.g., Go’s driver or the mongo shell—then you fetch that document with mongosh, you’ll see null where the actual stored document has undefined. 
2. Mentions that BSON undefined is deprecated everywhere, not just in `mongosh`. 
https://deploy-preview-365--docs-mongodb-shell.netlify.app/reference/compatibility/#undefined-values
https://jira.mongodb.org/browse/DOCSP-45255
[What's expected of an external …
> DOCSP-45255-mongosh-compatibility-changes-clarification

- snooty.toml
- source/changelog.txt
Adds 2.3.8 release notes. Per JIRA release ticket, no explicit release notes required (internal only).
https://deploy-preview-375--docs-mongodb-shell.netlify.app/changelog/#v2.3.8
https://jira.mongodb.org/browse/DOCSP-46185
> DOCSP-46185 Adds 2.3.8 release notes

- snooty.toml
- source/includes/list-table-shell-properties.rst
- source/logs.txt
- source/logs/location.txt
Users can now specify a custom location for shell log files.
- [Specify Log File Location](https://deploy-preview-379--docs-mongodb-shell.netlify.app/logs/location/)
- [Settings Table](https://deploy-preview-379--docs-mongodb-shell.netlify.app/reference/configure-shell-settings/#configurable-settings)
https://jira.mongodb.org/browse/DOCSP-47888
> DOCSP-47888-custom-log-location

- source/changelog.txt
- Adds CVE numbers and links for the 2.3.9 release notes
[Release Notes: 2.3.9](https://deploy-preview-380--docs-mongodb-shell.netlify.app/changelog/#v2.3.9)
NVD CVEs: [1691](https://nvd.nist.gov/vuln/detail/CVE-2025-1691), [1692](https://nvd.nist.gov/vuln/detail/CVE-2025-1692), [1693](https://nvd.nist.gov/vuln/detail/CVE-2025-1693)
https://jira.mongodb.org/browse/DOCSP-47856
> DOCSP-47856 Added CVE numbers and links

- source/includes/admonitions/note-redact-credentials-command-history.rst
- source/logs.txt
- source/logs/command-history.txt
- source/logs/view.txt
- source/reference.txt
- source/write-scripts.txt
Refactor logging landing page to split tasks into their own pages.
- [Shell Logs](https://deploy-preview-389--docs-mongodb-shell.netlify.app/logs/)
- [View Shell Logs](https://deploy-preview-389--docs-mongodb-shell.netlify.app/logs/view/) (No major copy changes here. Just moving the pre-existing copy to its own task page.)
- [View Command History](https://deploy-preview-389--docs-mongodb-shell.netlify.app/logs/command-history/) (No major copy changes here. Just moving the pre-existing copy to its own task page.)
https://jira.mongodb.org/browse/DOCSP-47901
> DOCSP-47901-refactor-logging-landing-page

- source/connect.txt
Add diff behaviors of database attributes in connection strings for both manual and mongosh. This PR handles the changes on Mongo Shell ([connect to a deploymet page](https://www.mongodb.com/docs/mongodb-shell/connect/#connect-to-a-specific-database))
Manual PR: https://github.com/10gen/docs-mongodb-internal/pull/11259
https://deploy-preview-385--docs-mongodb-shell.netlify.app/connect/#connect-to-a-specific-database
https://jira.mongodb.org/browse/DOCS-16967
> DOCSP-16967-inconsistent-connection-string-attribute-description

- source/includes/list-table-shell-properties.rst
Update [mongosh history log](https://www.mongodb.com/docs/mongodb-shell/reference/configure-shell-settings-global/#configurable-settings) descriptions. 
- https://deploy-preview-394--docs-mongodb-shell.netlify.app/reference/configure-shell-settings-global/#configurable-settings
- https://deploy-preview-394--docs-mongodb-shell.netlify.app/reference/configure-shell-settings-api/
https://jira.mongodb.org/browse/DOCSP-48522
> DOCSP-48522-update-mongosh-history-log-description

- source/includes/log-file-location.rst
- source/logs/custom-entries.txt
- source/logs/location.txt
- source/logs/view.txt
Starting in Mongo Shell 2.4.0, you can view the log file location in the
file system with the ``log.getPath()`` command, which also contains the session ID.
https://deploy-preview-395--docs-mongodb-shell.netlify.app/logs/view/#view-shell-logs
https://deploy-preview-395--docs-mongodb-shell.netlify.app/logs/location/#log-file-location
https://jira.mongodb.org/browse/DOCSP-47538
> DOCSP-47538-log-path-and-id

- source/connect.txt
Adds content to ``mongosh`` docs to support https://github.com/10gen/docs-mongodb-internal/pull/11511.
https://deploy-preview-398--docs-mongodb-shell.netlify.app/connect/#connect-to-a-replica-set
https://jira.mongodb.org/browse/DOCSP-48699
> DOCSP-48699-directConnection-Docker-admonition

- source/reference/methods.txt
Updates the reference/methods page to clarify how BatchSize works. Related to the [batchsize pr](https://github.com/mongodb/docs/pull/6292) in the docs repo. No new sections were added, but descriptions of BatchSize were changed.
Wording taken from already updated [PHP driver docs](https://jira.mongodb.org/browse/DOCSP-47835) which was approved by a PHP engineer. 
https://deploy-preview-392--docs-mongodb-shell.netlify.app/reference/methods/#cursor-methods
https://jira.mongodb.org/browse/DOCSP-47795
https://app.netlify.com/sites/docs-mongodb-shell/deploys/67d4525e66989c0008faf1e8
> [DOCSP-47795] Change batchsize description

- source/snippets/working-with-snippets.txt
Deleted the old URL that was linking to a personal GitHub repo.
https://deploy-preview-403--docs-mongodb-shell.netlify.app/snippets/working-with-snippets/
https://jira.mongodb.org/browse/DOCSP-49854
> DOCSP-49854-remove-old-url
