mongodb/docs-mongodb-shell

- source/connect.txt
- source/includes/steps-install-shell-macos.yaml
- source/index.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/9081b3e/mongodb-shell/docsworker/DOCSP-10357/
> macOS install instructions

- source/includes/steps-install-shell-base.yaml
- source/includes/steps-install-shell-generic-linux.yaml
- source/index.txt
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/db2c52b/mongodb-shell/docsworker/DOCSP-10360/#procedure) (Linux tab)
> (DOCSP-10360): generic linux install instructions

- source/connect.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-10355)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker/DOCSP-10355/connect)
This page will be updated with --host and --port options when https://jira.mongodb.org/browse/MONGOSH-219 is resolved.
> (DOCSP-10355) Connect to a Deployment

- source/index.txt
- source/run-agg-pipelines.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-10559)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker/DOCSP-10559/run-agg-pipelines#run-aggregation-pipelines)
@jeff-allen-mongo who is the tech reviewer for this?
> (DOCSP-10559): mdb-shell Aggregation Pipeline Tutorial

- source/reference/methods.txt
JIRA: [DOCSP-11603](https://jira.mongodb.org/browse/DOCSP-11603)
Staged: [Administration Methods](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11603/reference/methods#administration-methods)
Tested all of these, they work as expected.
> (DOCSP-11603): Add supported db admin methods

- source/reference/methods.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-11670)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11670/reference/methods#database-methods)
> DOCSP-11670: [MONGOSH] Support raw command execution methods

- source/reference/methods.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-11669)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-11669/reference/methods#database-methods)
> DOCSP-11669: [MONGOSH] Support Logging and profiling methods

- source/connect.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-10993)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-10666/connect#disconnect-from-a-deployment)
> (DOCSP-10666) Additional exit commands

- source/reference.txt
- source/reference/access-mdb-shell-help.txt
- source/reference/data-types.txt
- source/reference/methods.txt
- source/reference/options.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12214/reference/data-types
JIRA: https://jira.mongodb.org/browse/DOCSP-12211
> (DOCSP-12214): Add Data Types page

- source/reference/methods.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-12296)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12296/reference/methods#collection-methods)
> (DOCSP-12296) Add collection methods validate and mapReduce

- source/reference/methods.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-12636)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12636/reference/methods#replication-methods)
> DOCSP-12636 doc for Replica Set Status

- source/reference/methods.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-12661)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12661/reference/methods#replication-methods)
> DOCSP-12661 doc for Add Replica Set Members methods

- source/reference/methods.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-12664)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12664/reference/methods#replication-methods)
> DOCSP-12664 Replica Set Management methods

- source/reference/methods.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-12609)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-12577/reference/methods)
> [mongosh] sharding methods

- source/includes/admonitions/connection-resets.rst
- source/reference/methods.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-13313)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13313/reference/methods)
> DOCSP-13313: [MONGOSH] Investigate if reconnecting MongoClient will interfere with sessions

- source/reference/methods.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-13308)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13308/reference/methods#session-object-methods)
Also includes [DOCSP-13508](https://jira.mongodb.org/browse/DOCSP-13508), [DOCSP-13509](https://jira.mongodb.org/browse/DOCSP-13509), and [DOCSP-13510](https://jira.mongodb.org/browse/DOCSP-13510)
> DOCSP-13308: [MONGOSH] Create Session Object

- source/connect.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-13569)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13569/connect#connect-to-a-replica-set)
> DOCSP-13569: [MONGOSH] Mongosh fails to connect to node in state STARTUP2

- source/includes/steps-view-logs.yaml
- source/install.txt
- source/reference/methods.txt
- source/run-commands.txt
Jira:
https://jira.mongodb.org/browse/DOCSP-13662
https://jira.mongodb.org/browse/DOCSP-13741
https://jira.mongodb.org/browse/DOCSP-13749
https://jira.mongodb.org/browse/DOCSP-13739
Staged:
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-13662/
> DOCSP-13662: v0.7.0 updates

- source/reference/options.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-14024)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60231d79ab23346c203b952c)
[STAGING: OPTIONS](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-14024/reference/options/)
> (DOCSP-14024) Remove unimplemented mongosh options

- source/install.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-14365)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-14365/install/#procedure)
> DOCSP-14365 info for installing mongocryptd on linux

- source/reference/methods.txt
Staged: [Native Methods](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-15026/reference/methods/#native-methods)
> (DOCSP-15026): Load method

- source/reference/options.txt
JIRA: [DOCSP-15892](https://jira.mongodb.org/browse/DOCSP-15892)
Staged: [mongosh options](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-15892/reference/options/)
> (DOCSP-15892): Add --verbose and --quiet options

- source/reference/compatibility.txt
JIRA: [DOCSP-14221](https://jira.mongodb.org/browse/DOCSP-14221)
Staged: [Compatibility Changes](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-14221/reference/compatibility/)
> (DOCSP-15892): Read preference difference between mongosh and mongo

- source/reference/configure-shell-settings.txt
JIRA: [DOCSP-16215](https://jira.mongodb.org/browse/DOCSP-16215)
Staged: [Configure mongosh](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-16215/reference/configure-shell-settings/#configure-mongosh)
> (DOCSP-16215): inspectCompact property

- snooty.toml
- source/changelog.txt
- source/includes/steps-install-shell-macos.yaml
(DOCSP-17149): 0.15.1 release notes
> (DOCSP-17149): 0.15.1 release notes

- source/index.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-17293)
> (DOCSP-17293): enable :binary: links

- source/logs.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-17078)
[STAGED](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-17078/logs/#log-retention)
> (DOCSP-17078): mongosh retains logs for 30 days

- source/write-scripts.txt
JIRA: [DOCSP-17438](https://jira.mongodb.org/browse/DOCSP-17438)
Staging: [Write Scripts for mongosh](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-17438/write-scripts)
> (DOCSP-17438): Use 'built-in' instead of 'native' module

- source/connect.txt
> DOCSP-17839 point out that zstd and snappy are not available as compressor options

- source/changelog.txt
Hey @addaleax , could you take a look at these fixes to the 1.0.6 release notes? Thank you!
> (DOCSP-18675): Fix 1.0.6 release notes

- source/reference/options.txt
https://jira.mongodb.org/browse/DOCSP-17656
[MONGOSH] Add build info command line flag
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-17656-buildinfo-command-flag/reference/options/#general-options
> Docsp 17656 buildinfo command flag

- source/logs.txt
https://jira.mongodb.org/browse/DOCSP-18148
[MONGOSH] Convert mongosh log format to be similar to server log format
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-18148-convert-mongosh-log-format/logs/
> DOCSP-18148 convert mongosh log format

- source/changelog.txt
- source/includes/examples/ex-display-dbname-and-hostname.rst
- source/includes/examples/ex-display-line-numbers.rst
- source/includes/examples/ex-display-system-uptime.rst
- source/includes/fact-mongoshrc-loading.rst
- source/mongoshrc.txt
- source/reference/configure-shell-settings.txt
- source/run-commands.txt
- source/write-scripts.txt
https://jira.mongodb.org/browse/DOCSP-18980
Improve visibility of .mongoshrc section
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-18980-improve-mongoshrc-visibility/changelog/#v0.13.1
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-18980-improve-mongoshrc-visibility/mongoshrc/#std-label-mongoshrc-js
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-18980-improve-mongoshrc-visibility/write-scripts/#execute-code-from-a-configuration-file
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-18980-improve-mongoshrc-visibility/run-commands/#.mongoshrc.js-file
> DOCSP-18980 improve mongoshrc visibility

- snooty.toml
- source/changelog.txt
Jira:
https://jira.mongodb.org/browse/DOCSP-20447
Build:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61e7174ebcf82347e52ebdc2
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-20447-mongosh-1-1-9/changelog/
> Docsp-20447 mongosh 1 1 9

- source/changelog.txt
JIRA
https://jira.mongodb.org/browse/DOCSP-20589
Release note to accompany DOCSP-18668
STAGING
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-20589-release-notes-for-update/changelog/#v1.0.6
> DOCSP-20589-release-notes-for-param-update

- source/index.txt
- source/reference.txt
- source/reference/access-mdb-shell-help.txt
JIRA https://jira.mongodb.org/browse/DOCSP-20626     
[MONGOSH] Combine Help pages
STAGING
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-20626-combine-help-pages/reference/access-mdb-shell-help/
> DOCSP-20626 combine help pages

- source/includes/steps-install-shell-linux-rpm.yaml
Automatic architecture detection in RHEL baseurl.
> Automatic architecture detection

- snooty.toml
- source/changelog.txt
Jira:
https://jira.mongodb.org/browse/DOCSP-21478
Build:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6234a7b70ab54725f1236781
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-21478/changelog/
> DOCSP-21478 1.3.0 release notes

- source/index.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-22753-update-node-version/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-22753)
> DOCSP-22753 update Node.js version

- snooty.toml
- source/changelog.txt
Jira:
https://jira.mongodb.org/browse/DOCSP-23039
Build:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6298cfa17cf5397525660f39
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-23039/changelog/#v1.5.0
> DOCSP-23039 mongosh 1.5 release notes

- source/includes/steps-install-shell-base.yaml
- source/includes/steps-install-shell-linux-deb.yaml
- source/includes/steps-install-shell-linux-generic.yaml
- source/includes/steps-install-shell-linux-rpm.yaml
https://jira.mongodb.org/browse/DOCS-15299
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCS-15299-fips-mode-legacy-shell-install/install/#install-mongosh-1
> DOCS-15299 fips mode legacy shell install

- source/includes/steps-createkey-aws-kms.yaml
- source/includes/steps-createkey-azure-vault.yaml
- source/includes/steps-createkey-gcp-kms.yaml
- source/includes/steps-createkey-local-keyfile.yaml
- source/reference/methods.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-23879-build-errors-csfle/field-level-encryption/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23879)
> DOCSP-23879 csfle build failures

- source/includes/examples/ex-display-dbname-and-hostname.rst
- source/reference/customize-prompt.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-17205-dbase-name-in-prompt/reference/customize-prompt/#std-label-customize-the-mongosh-prompt
)
[JIRA](https://jira.mongodb.org/browse/DOCSP-17205)
> DOCSP-17205 dbase name in prompt

- snooty.toml
- source/changelog.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-24085
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-24085/changelog/#v1.5.2
> (DOCSP-24085): v1.5.2 release notes

- snooty.toml
- source/changelog.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-24108
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-24108/changelog/#v1.5.3
> (DOCSP-24108): v1.5.3 release notes

- snooty.toml
- source/changelog.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-24131
Staging: 
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-24131/changelog/#v1.5.4
> (DOCSP-24131): v1.5.4 release notes

- source/includes/list-table-shell-properties.rst
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-20842-disable-telemetry/reference/configure-shell-settings-global/#std-label-configure-settings-global)
[JIRA](https://jira.mongodb.org/browse/DOCSP-20842)
> DOCSP-20842 disable telemetry

- source/index.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-23090-linkto-download-center/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23090)
> DOCSP-23090 link to download center

- source/includes/examples/ex-eval-multi.rst
- source/includes/examples/ex-eval-output.rst
- source/reference/compatibility.txt
- source/reference/options.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-23367-multiple-eval-args/reference/options/#std-option-mongosh.--eval)
[JIRA](https://jira.mongodb.org/browse/DOCSP-23367)
> DOCSP-23367 multiple eval args

- source/reference/compatibility.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-17144-compatibility-via-snippet/reference/compatibility/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-17144)
> DOCSP-17144 compatibility via snippet

- source/reference/options.txt
[CSFLE Options](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-24872/reference/options/#client-side-field-level-encryption-options)
https://jira.mongodb.org/browse/DOCSP-24872
> DOCSP-24872 adds FLE options

- source/reference/compatibility.txt
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-25775/reference/compatibility/#compatibility-changes-with-legacy-mongo-shell
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63446c0e7aabe79449cb0612
> DOCSP-25775 fixes mongocompat snippet name

- snooty.toml
- source/changelog.txt
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-27269/changelog/
Build log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63bc9671dc742b91f21b4677
> (DOCSP-27269): v1.6.2 release notes

- snooty.toml
- source/changelog.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-27964-release-notes-1.8.0/changelog/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-27964)
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6400cfb405dd3cc8141adfdd)
> DOCSP-27964-release-notes-1.8.0

- source/reference/compatibility.txt
This was supposed to go in with https://github.com/mongodb/docs-mongodb-shell/pull/251 
[staging](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-28696-review-update/reference/compatibility/#objectid-methods-and-attributes)
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6424686866f244bf5777c3ec)  The build error will go away when the server merge happens
> DOCSP-28696 review update

- source/includes/intro-openssl-installs.rst
- source/includes/steps-install-shell-linux-deb.yaml
- source/includes/steps-install-shell-linux-rpm.yaml
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-29118-install-mongosh-with-openssl/install/#std-label-mdb-shell-install)
[JIRA](https://jira.mongodb.org/browse/DOCSP-29118)
[SERVER][Docs Feedback] Clarify mongosh install instructions on .deb
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64494d157efd2382b3bdcade)
> DOCSP-29118 install mongosh with openssl

- source/includes/list-table-shell-properties.rst
Updating default value for `forceDisableTelemetry` to false. 
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCS-15992/reference/configure-shell-settings/#configurable-settings
https://jira.mongodb.org/browse/DOCS-15992
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6467ce28df0f8173e913289e
> DOCS-15992 forceDisableTelemetry Default false

- snooty.toml
- source/changelog.txt
Release notes for mongosh 1.9.0 and 1.9.1.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31026/changelog/
- https://jira.mongodb.org/browse/DOCSP-30126
- https://jira.mongodb.org/browse/DOCSP-29952
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=646f7d04df0f8173e994382a
> (DOCSP-31026,DOCSP-29952): 1.9.0 1.9.1 release notes

- source/crud/update.txt
Fixed code block, updated nonexistent example to one that will actually update. 
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-30355-fix-code-blocks/crud/update/
https://jira.mongodb.org/browse/DOCSP-30355
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648b1faa67a273b8167a3366
> DOCSP-30355 Fixed Code Block

- snooty.toml
- source/changelog.txt
Per shell team, omitting mention of Atlas search item. Used wordage in the release notes as requested by shell team.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-30365-release-notes/changelog/#v1.10.0
https://jira.mongodb.org/browse/DOCSP-30365
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648b624d259a8493e5ab3609
> DOCSP-30365 release-notes

- snooty.toml
- source/changelog.txt
Release notes for v1.10.1
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-30757/changelog/
https://jira.mongodb.org/browse/DOCSP-30757
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64930607259a8493e5665935
> (DOCSP-30757): mongosh 1.10.1 release notes

- source/reference/methods.txt
4 helper links.
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCS-15979-new-auto-merge-shell-helpers/reference/method/#sharding
https://jira.mongodb.org/browse/DOCS-15979
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64948202423952aeb970d154
> DOCS-15979 new-auto-merge-shell-helpers

- source/reference/methods.txt
Documents the ``createEncryptedCollection`` method.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31024/reference/methods/#client-side-field-level-encryption-methods
https://jira.mongodb.org/browse/DOCSP-31024
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649c9433423952aeb967d817
> DOCSP-31019 document createEncryptedCollection method

- source/includes/steps-install-shell-base.yaml
- source/includes/steps-install-shell-linux-generic.yaml
- source/includes/steps-install-shell-macos.yaml
- source/includes/steps-install-shell-windows.yaml
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-30933-macos-install-instructions/install/#install-from-.zip-file-1)
[JIRA](https://jira.mongodb.org/browse/DOCSP-30993)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b9ab3087b3b360468955a3)
> DOCSP-30933 macos install instructions

- source/includes/fact-connect-prereqs.rst
- source/install.txt
[staging](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31771-install-landing-page/install/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-31771)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c407dc87b3b36046ef9d7b)
> DOCSP-31771 install landing page

- source/changelog.txt
1.10.2 and 1.10.3 Release Notes
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31464/changelog/
https://jira.mongodb.org/browse/DOCSP-31464
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c836a987b3b36046bb01ff
- [ x ] Is this free of any warnings or errors in the RST?
- [ x ] Is this free of spelling errors?
- [ x ] Is this free of grammatical errors?
- [ x ] Is this free of staging / rendering issues?
- [ x ] Are all the links working?
> DOCSP-31464: 1.10.2 and 1.10.3 Release Notes

- snooty.toml
- source/changelog.txt
- source/index.txt
- source/reference.txt
Adding userfacing changes to the v1.10.4 change log on release notes. Also moving the release notes page out of the reference drawer to the top level TOC from the index page.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31788/changelog/#v1.10.4
https://jira.mongodb.org/browse/DOCSP-31788
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d5328367dbe91010a0f368
> DOCSP-31788 v1.10.4 Release Notes

- source/includes/scripting/fact-require-ems-modules.rst
- source/write-scripts/require-external-modules.txt
- source/write-scripts/require-load-differences.txt
[files and modules](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32118-require-modules/write-scripts/require-external-modules/#require-an-npm-module)
[require v load](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32118-require-modules/write-scripts/require-load-differences/#require---packaging-considerations)
[JIRA](https://jira.mongodb.org/browse/DOCSP-32119)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d68de667dbe91010f5a03c)
> DOCSP-32118 require modules

- snooty.toml
- source/changelog.txt
v1.10.5 release notes
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32153/changelog/#v1.10.5
https://jira.mongodb.org/browse/DOCSP-32153?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64daa71b67dbe91010aa980d
> DOCSP-32153 v1.10.5 release notes

- snooty.toml
- source/changelog.txt
Release notes for mongosh 1.10.6.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32609/changelog/
https://jira.mongodb.org/browse/DOCSP-32609
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e8b6d624fcc731b46a5d50
> (DOCSP-32609): mongosh 1.10.6 release notes

- snooty.toml
- source/includes/links-urls/ejson.rst
- source/reference.txt
- source/reference/ejson.txt
- source/reference/ejson/parse.txt
- source/reference/ejson/stringify.txt
- source/run-commands.txt
[ejson landing](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31806-ejson-methods/reference/ejson/)
[parse](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31806-ejson-methods/reference/ejson/parse/)
[stringify](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31806-ejson-methods/reference/ejson/stringify/)
[run commands](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31806-ejson-methods/run-commands/#format-input-and-output)
[JIRA](https://jira.mongodb.org/browse/DOCSP-31806)
[BUILD]()
> DOCSP-31806 ejson methods

- source/changelog.txt
- source/includes/platform-limitations.rst
- source/install.txt
Update 2.0 changelog and install page with platform support.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32210-platforms-misc/changelog/#v2.0.0
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32210-platforms-misc/install/#supported-mongodb-versions
https://jira.mongodb.org/browse/DOCSP-32210
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e541f357e37806c560c198
> DOCSP-32210-platforms-misc

- source/changelog.txt
Shell updates for new constructors.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31860-binary-constructors-shell/changelog/#v2.0.0
https://jira.mongodb.org/browse/DOCSP-31860
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e4e67c57e37806c5446d69
> DOCSP-31860-binary-constructors-shell

- source/install.txt
Added details for JSON file.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-32189-programmatic-download-URL/install/#next-steps
https://jira.mongodb.org/browse/DOCSP-32189
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e6712957e37806c5ab3896
> DOCSP-32189-programmatic-download-URL

- source/changelog.txt
Add link to release notes in Jira per Anna's link.
https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-31754-release-notes/changelog/#v2.0.0
https://jira.mongodb.org/browse/DOCSP-31754
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ef8e4524fcc731b4e5688a
> DOCSP-31754-release-notes

- source/facets.toml
- source/reference/facets.toml
https://jira.mongodb.org/browse/DOCSP-32483
Hi @sarah-olson-mongodb - I missed this one on my list, which is truly the last one for your team.  Please merge if it looks good!
Thank you!
Sarah
> DOCSP-32483 programmatic tagging script for mongoshell repo

- source/changelog.txt
`mongosh` v2.0.1 release notes, changelog.
https://preview-mongodbjmdmongo.gatsbyjs.io/mongodb-shell/DOCSP-33078/changelog/#v2.0.1
https://jira.mongodb.org/browse/DOCSP-33078
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6503698624fcc731b43c4d3d
> DOCSP-33078 mongosh v2.0.1 release notes, changelog

- source/connect.txt
- [Connect to a Deployment](https://preview-mongodbdacharyc.gatsbyjs.io/mongodb-shell/DOCSP-32029/connect/)
- https://jira.mongodb.org/browse/DOCSP-32029
- [Clean Build Log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6508ba50492df295cf8cc434)
> (DOCSP-32029): Add procedure to connect to an Atlas deployment

- source/changelog.txt
- source/reference/ejson.txt
- source/reference/ejson/serialize.txt
Content for serialize method. Keep this in mind: for consistency, the new page follows the wordage style for the other pages in the EJSON section.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-32654-serialize-method/reference/ejson/#ejson
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-32654-serialize-method/reference/ejson/serialize/#ejson.serialize--
https://jira.mongodb.org/browse/DOCSP-32654
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65259f16885de6b26b46a925
> DOCSP-32654-serialize-method

- source/crud.txt
- source/reference/ejson.txt
- source/reference/ejson/deserialize.txt
Document EJSON deserialize method.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-32655-EJSON-deserialize/reference/ejson/deserialize/
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-32655-EJSON-deserialize/reference/ejson/
https://jira.mongodb.org/browse/DOCSP-32655
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=653306cf3ede3ec111b8a0c8
> DOCSP-32655-EJSON-deserialize

- source/reference/ejson/stringify.txt
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-32658-expand-replace-examples/reference/ejson/stringify/#use-a-function-to-transform-output-fields-in-nested-objects
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-32658-expand-replace-examples/reference/ejson/stringify/#use-a-function-to-replace-bson-strings
https://jira.mongodb.org/browse/DOCSP-32658
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654a80d35b686d6bd91650a5
> DOCSP-32658-expand-replace-examples

- source/reference/compatibility.txt
Typo fix in Compatibility page
https://preview-mongodbjocelynmendez1.gatsbyjs.io/mongodb-shell/DOCSP-34326/reference/compatibility/#--eval-behavior
https://jira.mongodb.org/browse/DOCSP-34326?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6554f0165b686d6bd9976c08
> DOCSP-34326 typo fix in Compatibility page

- snooty.toml
- source/changelog.txt
mongosh v2.1.0 release notes
https://preview-mongodbjocelynmendez1.gatsbyjs.io/mongodb-shell/DOCSP-34333/changelog/
https://jira.mongodb.org/browse/DOCSP-34333?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6564cbd913dc9d16ea800590
> DOCSP-34333 mongosh v2.1.0 release notes

- source/install.txt
Adding support for Oracle Linux 8+ running the Red Hat Compatible Kernel (RHCK).
https://preview-mongodbmmavillemdb.gatsbyjs.io/mongodb-shell/DOCSP-35170-mongosh-support-for-OEL/install/#supported-operating-systems
https://jira.mongodb.org/browse/DOCSP-35170
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=658344df77a86a479b751615
> DOCSP-35170-mongosh-support-for-OEL

- source/reference/methods.txt
Adds mongosh method sh.getShardedDataDistribution.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-25130-sharded-data-method/reference/methods/#sharding-methods
https://jira.mongodb.org/browse/DOCSP-25130
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=659600d6dcc0144a51e0310e
> DOCSP-25130-sharded-data-method

- snooty.toml
- source/changelog.txt
mongosh v2.1.4 release notes
https://preview-mongodbjocelynmendez1.gatsbyjs.io/mongodb-shell/DOCSP-36319/changelog/#v2.1.4
https://jira.mongodb.org/browse/DOCSP-36319
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c64e786b2f17c95a8d98a7
> DOCSP-36319 v2.1.4 release notes

- source/includes/steps-install-shell-linux-rpm.yaml
changing $releasever to 2023 for .repo file
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-shell/DOCSP-36565/install/#procedure-3
https://jira.mongodb.org/browse/DOCSP-36565
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c68f946b2f17c95aa79bec
> DOCSP-36565 fixing mongosh installation .repo file

- source/run-commands.txt
- source/write-scripts.txt
Adds information about how to exit a running script on exception or unexpected results.
https://preview-mongodbmongocaleb.gatsbyjs.io/mongodb-shell/DOCSP-26043/write-scripts/#terminate-a-script-on-error
https://jira.mongodb.org/browse/DOCSP-26043
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bbe37c6b2f17c95ac6db1e
> add section explaining the use of the exit() method

- source/changelog.txt
``mongosh`` 2.15 Release Notes, reworded a couple notes for additional context.
https://preview-mongodbianfmongodb.gatsbyjs.io/mongodb-shell/DOCSP-36866/changelog/#v2.1.5
https://jira.mongodb.org/browse/DOCSP-36866
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d4c16c71111659826d5f57
> DOCSP-36866 Mongosh 2.1.5 Release Notes

- source/reference/options.txt
- source/write-scripts.txt
Added file parameter per JIRA.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-36969-file-parameter/reference/options/#std-option-mongosh.--file
https://jira.mongodb.org/browse/DOCSP-36969
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65de322c7111165982d1c91a
> DOCSP-36969-file-parameter

- source/includes/fact-call-limitations.rst
document that Database operations using JavaScript setters in Classes don't work
https://preview-mongodbkanchanamongodb.gatsbyjs.io/mongodb-shell/DOCSP-26564/reference/compatibility/#limitations-on-database-calls
https://jira.mongodb.org/browse/DOCSP-26564
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ea013e11db7b04278c7fbf
> DOCSP-26564 document that Database operations in Classes don't work

- source/changelog.txt
Release Notes for MongoDB Shell 2.2.0. Please note this was originally submitted as 2.1.6 and upreved to 2.2.0 after adding some additional work items.
https://preview-mongodbmmavillemdb.gatsbyjs.io/mongodb-shell/DOCSP-37598-mongodb-shell-2.20-release/changelog/
https://jira.mongodb.org/browse/DOCSP-37598
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65fb47d36fc5f048506ae54f
> DOCSP-37598-mongodb-shell-2.20-release

- source/includes/fact-call-limitations.rst
Replacing `findMany()` with `findOne()`.
https://preview-mongodbianfmongodb.gatsbyjs.io/mongodb-shell/DOCSP-38397/write-scripts/considerations/#generator-functions
https://jira.mongodb.org/browse/DOCSP-38397
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6613e4f23a5920a29128fc57
> DOCSP-38397 Remove FindMany

- source/index.txt
Fixes mongosh landing page typo.
https://preview-mongodbjmdmongo.gatsbyjs.io/mongodb-shell/DOCSP-38691/
https://jira.mongodb.org/browse/DOCSP-38691
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661d361c3a5920a2915241b9
> DOCSP-38691 mongosh landing page typo

- source/changelog.txt
2.2.5 mongosh rn
https://preview-mongodbjocelynmendez1.gatsbyjs.io/mongodb-shell/DOCSP-38873/changelog/#v2.2.5
https://jira.mongodb.org/browse/DOCSP-38873?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6629512db67dbf804aed70bf
> DOCSP-38873 2.2.5 mongosh rn

- source/changelog.txt
v2.1.1 release notes.
https://preview-mongodbjmdmongo.gatsbyjs.io/mongodb-shell/DOCSP-34684/changelog/#v2.1.1
https://jira.mongodb.org/browse/DOCSP-34684
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66339542b67dbf804a4752e1
> DOCSP-34684 v2.1.1 release notes

- source/changelog.txt
2.2.9 changelog updates. 
Note to reviewers: This release does not include [user facing changes](https://mongodb.slack.com/archives/CUHC9R8J0/p1718378038131509). I've mentioned the node.js driver version bump, and included a link to the full release notes on consistency grounds. We generally include the release notes link, and I think it may be confusing to omit. Happy to delete if you disagree.
https://preview-mongodbsaraholsonmongodb.gatsbyjs.io/mongodb-shell/DOCSP-40374/changelog/#v2.2.9
https://jira.mongodb.org/browse/DOCSP-40374
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6675e75bebce19f314f71a30
> DOCSP-40374: 2.2.9 changelog updates

- source/changelog.txt
Shell release notes per JIRA. Will check with Anna when she's back. Might just need the link to the release notes in JIRA and nothing else.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/mongodb-shell/DOCSP-40766-shell-release-2.2.10/changelog/
https://jira.mongodb.org/browse/DOCSP-40766
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667b0926ebce19f31401fbc8
> DOCSP-40766-shell-release-2.2.10

- snooty.toml
- source/changelog.txt
mongosh 2.2.11 release notes
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-shell/DOCSP-41211/changelog/
https://jira.mongodb.org/browse/DOCSP-41211
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668d716afb8bd13b8477a81f
> DOCSP-41211 mongosh 2.2.11 release notes

- source/logs.txt
Fixing ndjson broken link 
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-shell/DOCSP-41412/logs/
https://jira.mongodb.org/browse/DOCSP-41412
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66902a32fb8bd13b841eb27a
> DOCSP-41412 fixing ndjson broken link

- snooty.toml
- source/changelog.txt
mongosh 2.2.12 release notes
https://preview-mongodbltranmdb2.gatsbyjs.io/mongodb-shell/DOCSP-41374/changelog/
https://jira.mongodb.org/browse/DOCSP-41374
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66913da3fb8bd13b84565ab1
> DOCSP-41374 mongosh 2.2.12 release notes

- source/changelog.txt
mongosh 2.2.6 release notes
https://preview-mongodbjocelynmendez1.gatsbyjs.io/mongodb-shell/DOCSP-39587/changelog/#v2.2.6
https://jira.mongodb.org/browse/DOCSP-39587
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=669813b226eba79552ce7cf6
> DOCSP-39587 mongosh 2.2.6 release notes

- source/changelog.txt
Update changelog to include Ubuntu 24.04 support
https://preview-mongodbjocelynmendez1.gatsbyjs.io/mongodb-shell/DOCSP-40118/changelog/#v2.2.7
https://jira.mongodb.org/browse/DOCSP-40118
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66a00cdb26eba795528a2662
> DOCSP-40118 Update changelog to include Ubuntu 24.04

- source/changelog.txt
Fix OpenSSL link causing 404
https://preview-mongodbjocelynmendez1.gatsbyjs.io/mongodb-shell/DOCSP-41783/changelog/#v1.3.1
https://jira.mongodb.org/browse/DOCSP-41783?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66a2b46426eba79552337cac
> DOCSP-41783 Fix OpenSSL link

- snooty.toml
- source/changelog.txt
- This ticket is for `2.2.13` but that release had no changes, see [2.2.13](https://github.com/mongodb-js/mongosh/releases/tag/v2.2.13) and [2.2.14](https://github.com/mongodb-js/mongosh/releases/tag/v2.2.14).
- Repurpose this ticket for the [2.2.15 ](https://github.com/mongodb-js/mongosh/releases/tag/v2.2.15)release notes instead.
- [See discussion in slack](https://mongodb.slack.com/archives/CUHC9R8J0/p1722338217968069).
https://preview-mongodbianfmongodb.gatsbyjs.io/mongodb-shell/DOCSP-41781/changelog/#v2.2.15
https://jira.mongodb.org/browse/DOCSP-41781
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66aa5d85824f175afd6f075a
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Docum …
> DOCSP-41781-Release-Notes-2-2-15

- source/connect.txt
Fixes a typo identified by our linguists. 
https://preview-mongodbsaraholsonmongodb.gatsbyjs.io/mongodb-shell/DOCSP-42099/connect/
https://jira.mongodb.org/browse/DOCSP-42099
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66ac0f16824f175afddf4beb
> DOCSP-42099: Typo fix

- snooty.toml
- source/changelog.txt
DOCSP-42626 mongosh 2.3.0 release notes
https://preview-mongodbjmdmongo.gatsbyjs.io/mongodb-shell/DOCSP-42626/changelog/#v2.3.0
https://jira.mongodb.org/browse/DOCSP-42626
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bf97748e811ae6727e27ff
> DOCSP-42626 mongosh 2.3.0 release notes

- source/connect.txt
- source/includes/table-proxy-env-variables.rst
- Documents proxy configuration environment variables
https://preview-mongodbajhuhmdb.gatsbyjs.io/mongodb-shell/DOCSP-42523-proxy-config-support/connect/#proxy-settings
https://jira.mongodb.org/browse/DOCSP-42523
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bfb7988e811ae67289d17d
> DOCSP-42523 Proxy Configuration Support

- source/write-scripts/require-external-modules.txt
Fixes a code typo on "Include External Files and Modules in Scripts".
https://preview-mongodbjmdmongo.gatsbyjs.io/mongodb-shell/DOCSP-43152/write-scripts/require-external-modules/#require-an-npm-module
https://jira.mongodb.org/browse/DOCSP-43152
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66cf988ec87522bd3a50a38d
> DOCSP-43152-fixes-mongosh-localRequire

- snooty.toml
- source/changelog.txt
Mongosh 2.3.1 Release Notes
https://deploy-preview-356--docs-mongodb-shell.netlify.app/changelog/
https://jira.mongodb.org/browse/DOCSP-43309
> DOCSP-43309: Initial 2.3.1 release notes

- source/configure-mongosh.txt
- source/crud.txt
- source/index.txt
- source/install.txt
- source/install/verify-signatures.txt
- source/reference.txt
- source/reference/configure-shell-settings.txt
- source/reference/ejson.txt
- source/snippets.txt
- source/snippets/reference.txt
- source/write-scripts.txt
Refactoring the ToC with the following guidelines: https://www.mongodb.com/docs/meta/style-guide/style/toc-labels/
https://deploy-preview-357--docs-mongodb-shell.netlify.app
https://jira.mongodb.org/browse/DOCSP-43308
> DOCSP-43308-toc-refactor

- source/crud/delete.txt
if you are dropping all documents from a large collection, dropping and recreating the collection is much faster
https://deploy-preview-358--docs-mongodb-shell.netlify.app/crud/delete/#delete-all-documents
https://jira.mongodb.org/browse/DOCSP-43957
> DOCSP-43957-recommend-drop-and-recreate

- source/reference/access-mdb-shell-help.txt
Removing nested component from `show dbs` table entry.
https://deploy-preview-359--docs-mongodb-shell.netlify.app/reference/access-mdb-shell-help/#command-helpers
https://jira.mongodb.org/browse/DOCSP-42972
> DOCSP-42972-mongosh-nested-components

- snooty.toml
- source/changelog.txt
Mongosh 2.3.2 release notes
https://deploy-preview-360--docs-mongodb-shell.netlify.app/changelog/#v2.3.2
https://jira.mongodb.org/browse/DOCSP-44209
> DOCSP-44209 MongoDB Shell 2.3.2 Release Notes

- source/changelog.txt
Release notes for mongosh 2.3.3
* [RN](https://deploy-preview-363--docs-mongodb-shell.netlify.app/changelog/#v2.3.3)
[DOCSP-44816](https://jira.mongodb.org/browse/DOCSP-44816)
> DOCSP-44816 mongosh 2.3.3. RN

- source/reference/methods.txt
Updates encryption methods title to cover all in-use encryption
https://deploy-preview-367--docs-mongodb-shell.netlify.app/reference/methods/#in-use-encryption-methods
https://jira.mongodb.org/browse/DOCSP-31157
> DOCSP-31157-encryption-methods-title-update

- source/changelog.txt
* Adds release notes for MongoDB Shell 2.3.4, [github relnotes available here](https://github.com/mongodb-js/mongosh/releases)
[Release Notes](https://deploy-preview-368--docs-mongodb-shell.netlify.app/changelog/#v2.3.4)
https://jira.mongodb.org/browse/DOCSP-45582
> DOCSP-45582 - MongoDB Shell 2.3.4 Release Notes

- source/reference/options.txt
Updates for security options per JIRA.
https://deploy-preview-369--docs-mongodb-shell.netlify.app/reference/options/#std-option-mongosh.--authenticationMechanism
https://jira.mongodb.org/browse/DOCSP-45454
> DOCSP-45454-oidc-ldap-shell

- source/includes/steps-install-shell-linux-deb.yaml
- source/install.txt
Add support and installation info for Ubuntu 24.04 (Noble Numbat)
https://deploy-preview-370--docs-mongodb-shell.netlify.app/install/#supported-platforms
https://deploy-preview-370--docs-mongodb-shell.netlify.app/install/#create-a-list-file-for-mongodb
https://jira.mongodb.org/browse/DOCSP-45772
> add Noble Numbat

- source/reference/methods.txt
Fixing build errors
https://deploy-preview-371--docs-mongodb-shell.netlify.app/reference/methods/#replication-methods
https://jira.mongodb.org/browse/DOCSP-46025
> DOCSP-46025-fixing-builds

- source/changelog.txt
We're not consistent in our use of fCV versus FCV. Let's standardize our docs set so that all instances are FCV. 
https://deploy-preview-372--docs-mongodb-shell.netlify.app/changelog/
[DOCSP-43739](https://jira.mongodb.org/browse/DOCSP-43739)
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 
> (DOCSP-43739) Standardize FCV

- source/reference/options.txt
Documents the `--oidcIDTokenAsAccessToken` option
https://deploy-preview-374--docs-mongodb-shell.netlify.app/reference/options/#std-option-mongosh.--oidcIdTokenAsAccessToken
https://jira.mongodb.org/browse/DOCSP-42038
> DOCSP-42038 OIDC ID Token Option

- snooty.toml
- source/logs.txt
- source/logs/custom-entries.txt
Document how to add custom log messages for mongosh
[Write Custom Log Entries](https://deploy-preview-378--docs-mongodb-shell.netlify.app/logs/custom-entries/)
https://jira.mongodb.org/browse/DOCSP-46885
> DOCSP-46885-custom-log-entries

- source/reference/access-mdb-shell-help.txt
Document help for log methods.
[Log Method Help](https://deploy-preview-383--docs-mongodb-shell.netlify.app/reference/access-mdb-shell-help/#log-method-help)
https://jira.mongodb.org/browse/DOCSP-47225
> DOCSP-47225-log-message-help

- snooty.toml
- source/includes/list-table-shell-properties.rst
- source/logs.txt
- source/logs/disable.txt
Document how to disable logging for the shell.
[Disable Logging](https://deploy-preview-381--docs-mongodb-shell.netlify.app/logs/disable/)
https://jira.mongodb.org/browse/DOCSP-47122
> DOCSP-47122-disable-logging

- source/includes/fact-certificate-expiry-warning.rst
x.509 -> X.509
- https://deploy-preview-382--docs-mongodb-shell.netlify.app/reference/options/#std-option-mongosh.--tlsCertificateKeyFile
https://jira.mongodb.org/browse/DOCSP-47586
> DOCSP-47586: Audit 1 file

- source/includes/list-table-shell-properties.rst
- source/logs.txt
- source/logs/compression.txt
- source/logs/location.txt
Document how to enable log compression
- [Settings table](https://deploy-preview-386--docs-mongodb-shell.netlify.app/reference/configure-shell-settings/#configurable-settings)
- [Enable log compression](https://deploy-preview-386--docs-mongodb-shell.netlify.app/logs/compression/)
https://jira.mongodb.org/browse/DOCSP-48000
> DOCSP-48000-log-compression

- snooty.toml
- source/includes/list-table-shell-properties.rst
- source/includes/log-retention-multiple-criteria.rst
- source/logs.txt
- source/logs/retention.txt
- source/logs/retention/duration.txt
Add a concept page for log retention and a task page for setting a custom log file duration. Note that we will be creating additional task pages for retaining logs based on file count and log file size.
- [Log Retention](https://deploy-preview-384--docs-mongodb-shell.netlify.app/logs/retention/)
- [Customize Log Retention Duration](https://deploy-preview-384--docs-mongodb-shell.netlify.app/logs/retention/duration)
- [Settings Table](https://deploy-preview-384--docs-mongodb-shell.netlify.app/reference/configure-shell-settings/)
https://jira.mongodb.org/browse/DOCSP-47935
> DOCSP-47935-log-retention-duration

- source/includes/platform-limitations.rst
removed mention of nodejs 16
https://deploy-preview-391--docs-mongodb-shell.netlify.app/install/
https://jira.mongodb.org/browse/DOCSP-47746
> DOCSP-47746-drop-nodejs-16

- source/changelog.txt
Release notes for 2.4.2.
[RN](https://deploy-preview-390--docs-mongodb-shell.netlify.app/changelog/#v2.4.2)
[DOCSP-48071](https://jira.mongodb.org/browse/DOCSP-48071)
> DOCSP-48071 2.4.2 RN

- source/reference/methods.txt
Adding upcoming methods to mongosh docs.
https://deploy-preview-393--docs-mongodb-shell.netlify.app/reference/methods/#sharding-methods
https://jira.mongodb.org/browse/DOCSP-48351
> DOCSP-48351: mongosh helper methods

- source/reference/options.txt
Add line to oidcTrustedEndpoint option clarifying why this option is a requirement
https://deploy-preview-399--docs-mongodb-shell.netlify.app/reference/options/
https://jira.mongodb.org/browse/DOCSP-48768
https://app.netlify.com/sites/docs-mongodb-shell/deploys/67f423239a0e4f00089f69d4
> DOCSP-48768-clarify-oidctrustedendpoint

- source/changelog.txt
2.5.0 release notes
https://deploy-preview-400--docs-mongodb-shell.netlify.app/changelog/
https://jira.mongodb.org/browse/DOCSP-49149
> DOCSP-49149-2.5.0-rn

- source/reference/methods.txt
- source/write-scripts/require-load-differences.txt
Remove pwd and cd commands
https://deploy-preview-402--docs-mongodb-shell.netlify.app/reference/methods/#native-methods
https://jira.mongodb.org/browse/DOCSP-49649
https://app.netlify.com/sites/docs-mongodb-shell/deploys/6813c91a01811300086d63c7
> DOCSP-49649-remove-pwd-cd
